# Generated by Django 6.0.3 on 2026-03-14 21:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_classe', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url_fichier', models.FileField(upload_to='documents/')),
                ('annee_academique', models.CharField(blank=True, max_length=9)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('statut_ai', models.CharField(choices=[('en_attente', 'En attente'), ('analyse', 'Analysé'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('statut_humain', models.BooleanField(default=False)),
                ('statut_doc', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('poids_fichier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validateur', models.TextField(blank=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.classe')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('URL_legal', models.URLField(blank=True)),
                ('nomLicence', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Licence',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Matière',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_niveau', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rôle',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.document')),
                ('numero_chapitre', models.IntegerField(blank=True, null=True)),
                ('est_resume_officiel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cours',
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.document')),
                ('session_examen', models.CharField(blank=True, max_length=50)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('type_examen', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Épreuve',
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.document')),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('maison_edition', models.CharField(blank=True, max_length=100)),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livre',
            },
            bases=('core.document',),
        ),
        migrations.AddField(
            model_name='document',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.licence'),
        ),
        migrations.AddField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.niveau'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateurs_custom', to='auth.group')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.role')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateurs_custom', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InteractionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('resume', 'Résumé'), ('qcm', 'QCM'), ('correction', 'Correction'), ('explication', 'Explication')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('prompt_utilisateur', models.TextField(blank=True)),
                ('contenu_genere', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_ia', to='core.document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_ia', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Interaction IA',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.utilisateur'),
        ),
    ]
