# Generated by Django 6.0.3 on 2026-03-19 04:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField(verbose_name='Énoncé de la question')),
                ('points', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Points')),
                ('explication', models.TextField(blank=True, help_text="Correction détaillée générée par l'IA", verbose_name='Explication de la réponse')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre dans le QCM')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ia.interactionia', verbose_name='Interaction IA source')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='documents.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_option', models.TextField(verbose_name="Texte de l'option")),
                ('est_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
            },
        ),
        migrations.CreateModel(
            name='SessionQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('score_obtenu', models.PositiveSmallIntegerField(default=0, verbose_name='Score obtenu')),
                ('score_total', models.PositiveSmallIntegerField(default=0, verbose_name='Score total possible')),
                ('nb_questions', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de questions')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_qcm', to='documents.document', verbose_name='Document source')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ia.interactionia', verbose_name='Interaction IA (QCM source)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_qcm', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session QCM',
                'verbose_name_plural': 'Sessions QCM',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReponseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('option_choisie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_session', to='quiz.optionreponse', verbose_name='Option choisie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_session', to='quiz.question', verbose_name='Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.sessionqcm', verbose_name='Session QCM')),
            ],
            options={
                'verbose_name': 'Réponse de session',
                'verbose_name_plural': 'Réponses de session',
            },
        ),
        migrations.AddIndex(
            model_name='sessionqcm',
            index=models.Index(fields=['utilisateur', 'statut'], name='quiz_sessio_utilisa_d56edd_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionqcm',
            index=models.Index(fields=['document', 'statut'], name='quiz_sessio_documen_bac72b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reponsesession',
            unique_together={('session', 'question')},
        ),
    ]
