# Generated by Django 6.0.3 on 2026-03-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='theme',
            field=models.CharField(choices=[('brownie', 'Brownie (chaud & sombre)'), ('midnight', 'Midnight (noir profond)'), ('arctic', 'Arctic (blanc épuré)'), ('forest', 'Forest (vert sombre)'), ('ocean', 'Ocean (bleu profond)'), ('rose', 'Rose (mauve chaud)')], default='brownie', max_length=20, verbose_name='Thème visuel'),
        ),
    ]
