# Generated by Django 6.0.3 on 2026-03-19 04:04

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_classe', models.CharField(max_length=100, verbose_name='Libellé de la classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'libelle_classe'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url_fichier', models.FileField(upload_to=documents.models.chemin_upload_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Fichier')),
                ('annee_academique', models.CharField(blank=True, help_text='Format : 2024-2025', max_length=9, verbose_name='Année académique')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('poids_fichier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (Mo)')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('statut_ia', models.CharField(choices=[('en_attente', 'En attente'), ('analyse', 'Analysé'), ('valide', 'Validé par IA'), ('rejete', 'Rejeté par IA')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut IA')),
                ('statut_humain', models.BooleanField(default=False, verbose_name='Validé humainement')),
                ('statut_doc', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé'), ('rejete', 'Rejeté')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut du document')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validateur', models.TextField(blank=True, verbose_name='Commentaire du validateur')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.classe', verbose_name='Classe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Auteur/Uploadeur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_licence', models.CharField(max_length=150, unique=True, verbose_name='Nom de la licence')),
                ('description', models.TextField(verbose_name='Description')),
                ('url_legal', models.URLField(blank=True, help_text='Lien vers le texte officiel de la licence', verbose_name='URL légale')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['nom_licence'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=150, unique=True, verbose_name='Nom de la matière')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom_matiere'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_niveau', models.CharField(max_length=100, unique=True, verbose_name='Libellé du niveau')),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['libelle_niveau'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('numero_chapitre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numéro de chapitre')),
                ('est_resume_officiel', models.BooleanField(default=False, verbose_name='Est un résumé officiel')),
                ('titre_chapitre', models.CharField(blank=True, max_length=200, verbose_name='Titre du chapitre')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('session_examen', models.CharField(blank=True, help_text='Ex : Juin 2024, Session normale', max_length=100, verbose_name="Session d'examen")),
                ('duree', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('type_examen', models.CharField(choices=[('BAC', 'BAC'), ('BTS', 'BTS'), ('PROBATOIRE', 'Probatoire'), ('BEPC', 'BEPC'), ('DEVOIR', 'Devoir'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'examen")),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('maison_edition', models.CharField(blank=True, max_length=150, verbose_name="Maison d'édition")),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_fichier', models.ImageField(upload_to='documents/images/%Y/', verbose_name='Fichier image')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Résolution')),
                ('annee_academique', models.CharField(blank=True, max_length=9, verbose_name='Année académique')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('statut_ai', models.CharField(default='en_attente', max_length=20, verbose_name='Statut IA')),
                ('statut_humain', models.BooleanField(default=False, verbose_name='Validé humainement')),
                ('statut_doc', models.CharField(default='brouillon', max_length=20, verbose_name='Statut')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('poids_fichier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (Mo)')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date validation')),
                ('commentaire_validateur', models.TextField(blank=True, verbose_name='Commentaire validateur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.licence', verbose_name='Licence'),
        ),
        migrations.AddField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.matiere', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='documents.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('qcm', 'QCM passé'), ('resume', 'Résumé demandé')], max_length=20, verbose_name="Type d'action")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('duree_consultation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de consultation (secondes)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur', 'type_action'], name='documents_a_utilisa_aa3175_idx'), models.Index(fields=['document', 'type_action'], name='documents_a_documen_b791d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evaluer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1–5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_avis', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='documents.document', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_avis'],
                'unique_together': {('utilisateur', 'document')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['statut_doc', 'matiere'], name='documents_d_statut__69a893_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['statut_doc', 'classe'], name='documents_d_statut__0e71bc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['utilisateur', 'statut_doc'], name='documents_d_utilisa_44be57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('libelle_classe', 'niveau')},
        ),
    ]
