# Generated by Django 6.0.3 on 2026-03-19 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('resume', 'Résumé automatique'), ('qcm', 'Génération de QCM'), ('correction', 'Correction détaillée'), ('explication', 'Explication de cours')], db_index=True, max_length=20, verbose_name="Type d'interaction")),
                ('moteur_ia', models.CharField(choices=[('gemini', 'Google Gemini'), ('huggingface', 'Hugging Face'), ('local', 'Modèle local')], default='gemini', max_length=20, verbose_name='Moteur IA utilisé')),
                ('prompt_utilisateur', models.TextField(blank=True, verbose_name="Prompt envoyé à l'IA")),
                ('contenu_genere', models.TextField(blank=True, verbose_name="Contenu généré par l'IA")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('duree_secondes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée de génération (s)')),
                ('tokens_utilises', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens utilisés')),
                ('succes', models.BooleanField(default=True, verbose_name='Succès')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur (si échec)")),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_ia', to='documents.document', verbose_name='Document source')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_ia', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Interaction IA',
                'verbose_name_plural': 'Interactions IA',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur', 'type_interaction'], name='ia_interact_utilisa_9d39ac_idx'), models.Index(fields=['document', 'type_interaction'], name='ia_interact_documen_07897b_idx'), models.Index(fields=['type_interaction', 'succes'], name='ia_interact_type_in_353630_idx')],
            },
        ),
    ]
