# Generated by Django 6.0.3 on 2026-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionia',
            name='moteur_ia',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('huggingface', 'Hugging Face'), ('deepseek', 'DeepSeek R1'), ('local', 'Modèle local')], default='gemini', max_length=20, verbose_name='Moteur IA utilisé'),
        ),
    ]
